name: Build and Release Tweak

on:
  push:
    paths:
      - ".github/workflows/rootless.yml"
      - "Tweak.x"
  workflow_dispatch:

jobs:
  build:
    name: Build tweak
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install brew gmake
        run: brew install make

      - name: Install Theos
        run: bash -c "$(curl -fsSL 'https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos')"

      - name: Setup Theos environment
        run: echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Make tweak
        run: gmake -j$(sysctl -n hw.ncpu) package
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: estrogen
          path: ./packages/*.deb

      - name: Delete old release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: estrogen
          path: ./artifacts/

      - name: Create new rolling release
        uses: ncipollo/release-action@v1
        with:
          name: "Estrogen Release"
          body: "This is a 'parody' and custom build of `flameaway/RemoveConfidential`.\nDo not use this `.deb` file unless you're content with the text in `Tweak.x`."
          artifacts: "./artifacts/*.deb"
          tag: release
          token: ${{ secrets.GITHUB_TOKEN }}
